---
- name: instalÂ·lar nginx
  become: yes
  hosts: webservers
  tasks:
    - include: env-preparation-playbook.yml
    - include: nginx-playbook.yml
    - include: deploy-playbook.yml 

  handlers:
    - include: nginx-handler.yml
...
